export const SIGNIN = '/sign-in/'
export const SIGNUP = '/sign-up/'
export const PROFILE = '/profile/'
export const LIST = '/articles/'
export const CREATE = '/new-article/'
export const ARTICLE = '/articles/:slug/'
export const EDIT = '/articles/:slug/edit/'
